---
- name: Download kube-burner git repo
  get_url:
    url: "https://github.com/kube-burner/kube-burner/releases/download/v{{ kube_burner_version }}/kube-burner-V{{ kube_burner_version }}-linux-ppc64le.tar.gz"
    dest: "/tmp/kube-burner-V{{ kube_burner_version }}-linux-ppc64le.tar.gz"
    mode: '0644'  

- name: Extract kube-burner tarball
  unarchive:
    src: "/tmp/kube-burner-V{{ kube_burner_version }}-linux-ppc64le.tar.gz"
    dest: "/tmp/"
    remote_src: yes  # Use to indicate the file is already on the remote machine
    creates: "/tmp/kube-burner-V{{ kube_burner_version }}-linux-ppc64le"  # Prevent extraction if the folder already exists

- name: Verify extracted files
  command: ls -la /tmp/ | grep kube-burner
  register: result
  failed_when: result.rc == 0

- name: Move the kube-burner executable to /bin
  command: "mv /tmp/kube-burner /bin/"

- name: kube-burner version
  shell: /bin/kube-burner version

