---
# defaults file for playbooks/roles/ocp-sso
sso_enabled: false
sso_catalogsource: "redhat-operators"
sso_directory: "/tmp/sso"
sso_catalogsource_image: ""
sso_upgrade_channel: "stable"
sso_schedulerImage: "registry.k8s.io/scheduler-plugins/kube-scheduler:v0.30.6"
sso_go_tarball: "https://go.dev/dl/go1.22.4.linux-ppc64le.tar.gz"
sso_e2e: false
sso_e2e_github_repo: "https://github.com/openshift/openshift-tests-private.git"
sso_e2e_github_branch: "master"
sso_github_username: ""          
sso_github_token: ""
sso_cleanup: true
